# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  
dependencies:
  override:
    - curl https://install.meteor.com | /bin/sh
    - meteor npm install

jobs:
  one:
    docker:
      - image: cimg/node:15
    steps:
      - checkout
      - run: npm run test

workflows:
  version: 2
  run_jobs:
    jobs:
      - one